swagger: "2.0"
info:
  description: "iClinic Python Challenge - implementation of the challenge as in
  [this project](https://github.com/iclinic/iclinic-python-challenge). The full project is available at
  [https://github.com/samueljoaquim/prescriptions](https://github.com/samueljoaquim/prescriptions)."
  version: "1.0.0"
  title: "Prescriptions API"
tags:
- name: "prescriptions"
  description: "Prescriptions API"
paths:
  /prescriptions:
    post:
      tags:
      - "prescriptions"
      summary: "Validate clinic, physician and patient ids, save metrics and
      return the prescription request data with and added id"
      description: ""
      operationId: "addPrescription"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Input with clinic, physician and patient IDs"
        required: true
        schema:
          $ref: "#/definitions/PrescriptionInput"
      responses:
        "200":
          description: "Prescription created"
          schema:
            $ref: "#/definitions/PrescriptionOutput"
        "405":
          description: "Malformed request"
          schema:
            $ref: "#/definitions/PrescriptionErrorMsg"
        "404":
          description: "One of the entities was not found"
          schema:
            $ref: "#/definitions/PrescriptionErrorMsg"
        "503":
          description: "One of the dependent services is unavailable"
          schema:
            $ref: "#/definitions/PrescriptionErrorMsg"
        "500":
          description: "An unknown application error has occurred"
          schema:
            $ref: "#/definitions/PrescriptionErrorMsg"
definitions:
  PrescriptionInput:
    type: "object"
    required:
    - "clinic"
    - "physician"
    - "patient"
    - "text"
    properties:
      clinic:
        type: "object"
        required:
        - "id"
        properties:
          id:
            type: integer
            format: "int64"
      physician:
        type: "object"
        required:
        - "id"
        properties:
          id:
            type: integer
            format: "int64"
      patient:
        type: "object"
        required:
        - "id"
        properties:
          id:
            type: integer
            format: "int64"
      text:
        type: "string"
  PrescriptionOutput:
    type: "object"
    required:
    - "data"
    properties:
      data:
        type: object
        required:
        - "id"
        - "clinic"
        - "physician"
        - "patient"
        - "text"
        properties:
          id:
            type: "object"
          clinic:
            type: "object"
            required:
            - "id"
            properties:
              id:
                type: integer
                format: "int64"
          physician:
            type: "object"
            required:
            - "id"
            properties:
              id:
                type: integer
                format: "int64"
          patient:
            type: "object"
            required:
            - "id"
            properties:
              id:
                type: integer
                format: "int64"
          text:
            type: "string"
  PrescriptionErrorMsg:
    type: "object"
    required:
    - "error"
    properties:
      error:
        type: "object"
        required:
        - "code"
        - "message"
        properties:
          code:
            type: string
          message:
            type: string
