# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Prescriptions Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      working-directory: ./app
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        pipenv install --dev
    - name: Test with Nose
      working-directory: ./app
      env:
        PRESCRIPTIONS_MONGODB_URI: mongodb://prescriptionsdb:27017
        PRESCRIPTIONS_MONGODB_OP_TIMEOUT: 15000
        PRESCRIPTIONS_MONGODB_CON_TIMEOUT: 10000
        PRESCRIPTIONS_ENDPOINT: https://5f71da6964a3720016e60ff8.mockapi.io/v1
        PRESCRIPTIONS_PHYSICIAN_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyLCJzZXJ2aWNlIjoicGh5c2ljaWFucyJ9.Ei58MtFFGBK4uzpxwnzLxG0Ljdd-NQKVcOXIS4UYJtA
        PRESCRIPTIONS_PHYSICIAN_TIMEOUT: 4
        PRESCRIPTIONS_PHYSICIAN_RETRIES: 2
        PRESCRIPTIONS_PHYSICIAN_PATH: /physicians/{id}
        PRESCRIPTIONS_PATIENT_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyLCJzZXJ2aWNlIjoicGF0aWVudHMifQ.Pr6Z58GzNRtjX8Y09hEBzl7dluxsGiaxGlfzdaphzVU
        PRESCRIPTIONS_PATIENT_TIMEOUT: 3
        PRESCRIPTIONS_PATIENT_RETRIES: 2
        PRESCRIPTIONS_PATIENT_PATH: /patients/{id}
        PRESCRIPTIONS_METRICS_TOKEN: SflKxwRJSMeKKF2QT4fwpMeJf36POk6yJV_adQssw5c
        PRESCRIPTIONS_METRICS_TIMEOUT: 6
        PRESCRIPTIONS_METRICS_RETRIES: 5
        PRESCRIPTIONS_METRICS_PATH: /metrics
        PRESCRIPTIONS_CLINIC_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyLCJzZXJ2aWNlIjoiY2xpbmljcyJ9.r3w8KS4LfkKqZhOUK8YnIdLhVGJEqnReSClLCMBIJRQ
        PRESCRIPTIONS_CLINIC_TIMEOUT: 5
        PRESCRIPTIONS_CLINIC_RETRIES: 3
        PRESCRIPTIONS_CLINIC_PATH: /clinics/{id}
      run: |
        pipenv run nosetests --with-coverage --cover-package=api,services,models,exceptions
      
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build Docker Image
      env:
        IMAGE_TAG: ${{ github.sha }}
      run:
        docker build . -t "prescriptions:$IMAGE_TAG"